// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package case2

// Injectors from wire.go:

func InitMission(name string) Game {
	player := NewPlayer(name)
	monster := NewMonster()
	game := NewGame(player, monster)
	return game
}
